- job_name: blackbox
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
        - http://18.188.233.96 # EC2 Instance Public IP
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: prometheus-blackbox-exporter.monitoring:9115
- job_name: node_exporter
  static_configs:
   - targets:
       - 10.100.10.141:9100
